server:
  api: 'http://127.0.0.1:5000'

constants:
  cond: ["NS", "FN", "NE", "N", "OH", "SV", "AR", "NQ"]
  cert_source: ["129 Trace", "EASA F1", "FAA 8130-3", "JAA F1", "145 Trace", "Company C of C", "OEM", "None"]
  delivery: ["1 week", "2 weeks", "3 weeks", "4 weeks", "6 weeks", "8 weeks", "10 weeks", "12 weeks",
             "1 day", "2 days", "3 days", "4 days", "5 days", "6 days", "NQ"]
  currency: ["Euro", "Dollar"]
  prepared_by: ['Prepared by 1', 'Prepared by 2']
  fob: ['Hannover', 'Berlin', 'UK']
  terms_of_payment: ['Net 30 days']
  minimum_order: ['None, unless specified.']

template:
  logo_dir: 'excel-files/logo.png'
  quote:
    dir: 'excel-files/templates/quote/aat'
    shrink_to_items: 'no'
  invoice:
    dir: 'template-ID-2'
    shrink_to_items: 'no'

database:
  dir: 'excel-files/database'
  rfq:
    db_headers: [ 'item_id', 'pn', 'desc', 'qty', 'customer_ref', 'cond', 'offer', 'date', 'contact', 'company', 'priority' ]

  inventory:
    db_headers: [ 'pn', 'desc', 'qty', 'cond', 'price', 'supplier', 'date', 'delivery' ]


issuing:
  auto_set_ship_to: true
  quote:
    output_dir: 'excel-files/quotes'
    id:
      prefix: 'QAZ/'
      length: 6
  purchase_order:
    output_dir: 'excel-files/quotes'
    id:
      prefix: 'PAZ/'
      length: 6

view:
  table:
    pagination: [100, 200, 'all']